### ISSUE TITLE
Currently no results are shown in the categories.

### ISSUE THREAD

**Issue by seizu** [seizu/plugin.video.filmpalast.ex#1]
Due to the Cloudflare Anti-Bot protection, FP cannot be parsed at the moment.

**Comment by carlo1312** [comment]
Hope there will be a solution soon... for me the best addon. Thanks for your work.

**Comment by seizu** [comment]
FP has currently deactivated Cloudflare protection. The plugin is working again.

**Comment by carlo1312** [comment]
I see. Made my day. Haha
